apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels:
    app: flaskapp 
spec:
  containers:
  - name: flask
    image: sumin819/flaskapp:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
  - name: docker-pull-secret
